[package]
name = "jank-crypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotlib = "0.5"
hex = "0.4.3"
rand = "0.8.5"
indicatif = "0.16.2"
chrono = "0.4.19"